[package]
name = "icecream"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"] # Говорим, что мы делаем C-совместимую динамическую библиотеку
name = "steam_api"

[dependencies]
chrono = "0.4.42"
ctor = "0.6.0"
ini = "1.3.0"
libloading = "0.8.9" 
once_cell = "1.21.3"
